print("Hello, answer the following questions for a cool cooking recipe!")
print()
type = input("Name a type of food: ")
plant = input("Name a plant: ")
cooking = input("Name a method of cooking (boil, saute, grill): ")
adjective = input("Give me a cool adjective: ")
item = input("And finally, a household item: ")
print()
print("Generating super cool recipe...")
print(".")
print(".")
print(".")
print("Recipe:", cooking, type, "with", adjective, plant, "served on a elegant", item)